### ISSUE TITLE
File name used for document is too long , exit code: 255

### ISSUE THREAD

**Issue by fergfamster** [aws-samples/amazon-textract-queries-example#1]
getting an error on training the classifier, appears the training UI has changed since the last update of this repo

**Comment by alam-bilal** [comment]
This is the classifier in Comprehend? When training with the "trainer.csv" file?

**Comment by alam-bilal** [comment]
I did a test run and creating a custom classifier with the supplied "trainer.csv" worked fine. Also was able to bring up the endpoint and run the step-function to process a PDF.
