### ISSUE TITLE
Update Requirements.txt to newer version of CDK and Lambda

### ISSUE THREAD

**Issue by fergfamster** [aws-samples/amazon-textract-queries-example#2]
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400.

I am guessing we need to update teh following to something like
aws-cdk-lib==2.81.0
constructs>=10.0.0,<11.0.0
aws_cdk.aws_lambda_python_alpha==2.24.1a0  (this needs?...)

aws-cdk-lib==2.24.1
constructs>=10.0.0,<11.0.0
aws_cdk.aws_lambda_python_alpha==2.24.1a0

**Comment by alam-bilal** [comment]
This has been updated.
